name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pyinstaller 
      run: |
        pyinstaller test.py --onefile
        version_number=$GITHUB_RUN_NUMBER
        time=$(date)
        printf "VERSION NUMBER: ${version_number}\nVERSION_TIME: ${time}\n" > ./version.properties
    - uses: actions/upload-artifact@v1
      with:
        name: executable
        path: .
