name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pyinstaller 
      run: |
        pyinstaller test.py --onefile --hidden-import='PIL._tkinter_finder'
        version_number=$GITHUB_RUN_NUMBER
        time=$(date +'$d-$m-$Y $H:$M:$S')
        printf "VERSION NUMBER: ${version_number}\nVERSION_TIME: ${time}\n" > ./version.properties
    - uses: actions/upload-artifact@v1
      with:
        name: executable
        path: ./dist/test
#   release:
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#     - uses: actions/checkout@master
#     - name: Create release
#       uses: anantmoudgalya/github-create-release-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Create GitHub release
#       uses: anantmoudgalya/github-upload-release-artifacts-action@master
#       with:
#         name : executable
# #         - dist/bin/
# #         - dist/shell/compiled.sh
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
