name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pyinstaller 
      run: |
        pyinstaller test.py --onefile --hidden-import='PIL._tkinter_finder'
        @echo off 
        echo/Today is: %year%-%month%-%day% 
        goto :EOF 
        setlocal ENABLEEXTENSIONS 
        set t = 2&if "%date%z" LSS "A" set t = 1 

        for /f "skip=1 tokens = 2-4 delims = (-)" %%a in ('echo/^|date') do ( 
           for /f "tokens = %t%-4 delims=.-/ " %%d in ('date/t') do ( 
              set %%a=%%d&set %%b=%%e&set %%c=%%f)) 
        endlocal&set %1=%yy%&set %2=%mm%&set %3=%dd%&goto :EOF
    - uses: actions/upload-artifact@v1
      with:
        name: CARE_files
        path: ./dist/
#   release:

#         echo COMMIT ID: $GITHUB_SHA
#         echo BRANCH REF: $GITHUB_REF
#         echo VERSION NUMBER: $GITHUB_RUN_NUMBER
#     runs-on: ubuntu-latest
#     needs: [build]
#     steps:
#     - uses: actions/checkout@master
#     - name: Create release
#       uses: anantmoudgalya/github-create-release-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: Create GitHub release
#       uses: anantmoudgalya/github-upload-release-artifacts-action@master
#       with:
#         name : executable
# #         - dist/bin/
# #         - dist/shell/compiled.sh
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
